name: Bug Report
description: File a bug report
title: "Bug report"
labels: ["bug"]
assignees:
  - hinell
body:
  - type: textarea
    id: issue-summary
    attributes:
      label: Summary
      placeholder: "Be brief, time is invaluable commodity that only few can afford"
    validations:
      required: true
  - type: textarea
    id: issue-repro
    attributes:
      label: Steps to reproduce
      placeholder: Specify how to reproduce issue if there are any ways
    validations:
      required: false
  - type: textarea
    id: issue-env
    attributes:
      label: Versions
      placeholder: |
        Specify all relevant VERSIONS and commits, e.g.:
        NVIM v0.10.0-dev-ac1c23442f
        Build type: MinSizeRel
        LuaJIT 2.1.0-beta3
    validations:
      required: false
